title: My Portfolio
description: >- 
  Hi! My name is Brittney, and welcome to my personal website where I showcase my projects.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme